[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Display the 10 slowest tests
addopts = -v --durations=10

# Ignore warnings from TensorFlow
filterwarnings =
    ignore::FutureWarning
    ignore::DeprecationWarning
    ignore::UserWarning

# Organize output by test name
console_output_style = classic 